rootProject.name = "ulgencs3"

// 6 Ana Anime Eklentisi
include(":TurkAnimeProvider")
include(":AnimeCixProvider")
include(":AnizmProvider")
include(":AniziumProvider")
include(":OpenAnimeProvider")
include(":TrAnimeIzleProvider")

// Dizi & Film Eklentileri (Mevcut)
include(":FilmModuProvider")
include(":HDFilmCehennemiProvider")
include(":DiziPalProvider")

// Yeni Entegre Edilen Dizi, Film ve TV Eklentileri
include(":DiziBoxProvider")
include(":DizillaProvider")
include(":SezonlukDiziProvider")
include(":DiziMomProvider")
include(":FilmMakinesiProvider")
include(":FullHDFilmizleseneProvider")
include(":InatBoxProvider")
include(":RecTVProvider")
include(":SelcukFlixProvider")
include(":WebteIzleProvider")
include(":CizgiMaxProvider")
include(":BelgeselXProvider")
include(":DdiziProvider")
include(":DiziKoreaProvider")
include(":JetFilmizleProvider")
include(":KultFilmlerProvider")
include(":SetFilmIzleProvider")
include(":SinemaCXProvider")
include(":SinewixProvider")
